title: PoLet500
author:
  name: Polemiche Letterarie del Cinquecento
  email: 'polemicheletterarie@gmail.com'
blog:
  route: '/testi/'
metadata:
    title: 'PoLet500 - Polemiche Letterarie del 500'
    description: 'PoLet500 Ã¨ un progetto in costruzione di schedatura telematica di polemiche letterarie del Cinquecento italiano'
taxonomies: [category,tag,month,char,author,chronology]
redirects:
    /changelog: /testi/the-urban-jungle
routes:
    /something/else: /testi/focus-and-blur
    /another/one/(.*): /testi/$1

